################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Design center product for Fiserv teams to loan.
# getStarted: "docs/getting-started.md"
benefits:
  - title: Transform
    description: Lorem ipsum dolor, consectetur sio adipiscing elit. Lorem ipsum dolor sit
  - title: Accelerate
    description: Intelligent design system
  - title: Optimize
    description: Lorem ipsum dolor, consectetur sio adipiscing elit. Lorem ipsum dolor sit
guides:
  - title: How to create API key
    description: Lorem ipsum dolor, consectetur sio adipiscing elit. Lorem ipsum dolor sit
    link: docs/release-notes/2022/march.md
  - title: How to create Merchant ID
    description: Lorem ipsum dolor, consectetur sio adipiscing elit. Lorem ipsum dolor sit
    link: docs/documentation/documentation.md
featuredFeatures:
  - title: Featured Product Offering
    description:  Lorem ipsum dolor, consectetur sio adipiscing elit. Lorem ipsum dolor sit
    groupName: Group Title
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME1.md
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
  - title: Product Offering
    description:  Lorem ipsum dolor, consectetur sio adipiscing elit. Lorem ipsum dolor sit
    groupName: Another Group Title
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME1.md
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
