################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: The Point Design System by Fiserv reflects the unique needs and priorities of designing for a complex, business-focused environment. Flash puts the user first, utilizing rigorous research into users’ needs and desires. It is laser-focused on real people.
# getStarted: "docs/getting-started.md"
benefits:
  - title: User-Centered Efficiency
    description: The Point Design System by Fiserv is rooted in user-centric principles, with a focus on efficiency and productivity.
  - title: Accelerate
    description: Clarity and consistency are paramount in our design system. We prioritize clean design elements and maintain a consistent look and feel.
  - title: Data-Driven Design
    description: Our design ethos values data-driven decision-making, ensuring that our interfaces present information in a meaningful and actionable way. 
guides:
  - title: Getting access to Figma
    description: Learn about how to get access to Point Design System Figma file. 
    link: "docs/getting-started.md#getting-access-to-figma"
featuredFeatures:
  - title: Foundations
    description:  Foundations are the core of the system, encapsulating the brand's principles and distinctions, along with the essential visual elements required to craft engaging end-to-end user experiences. This encompasses guidance on iconography, typography, layout, and structure.
    groupName: Group Title
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: "docs/design-files/foundations.md"
  - title: Components
    description:  Components are the reusable building blocks of our design system. Each component fulfills a specific interaction or UI need and has been intentionally crafted to seamlessly work together, creating patterns and delivering intuitive user experiences.
    groupName: Group Title
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: "docs/design-files/components.md"
  - title: Patterns
    description:  Patterns are reusable combinations of components and templates that address common user issues. These best practice solutions assist users in achieving their objectives and contribute to a consistent user experience.
    groupName: Group Title
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: "docs/design-files/patterns.md"
